### ISSUE TITLE
Creates a mesh for each wall in the maze ?

### ISSUE THREAD

**Issue by AdriCilie** [Gorgious56/MazeGenerator#14]
Is it possible to create several mesh with MazeGenerator?
That is to say for example to create a mesh to separate all the Walls to the maze? 

Thanks in advance

**Comment by Gorgious56** [comment]
If I'm not mistaken you can select the walls object, go into edit mode, select everything with A, then go Vertex > Rip Vertices (or shortcut V), then Mesh > Separate > By loost parts (or shortcut P) and it should create a different mesh per wall span

**Comment by AdriCilie** [comment]
Thank you for your quick response. 
I will try to realize your description, if it works you are a genius!
Thanks again! I would like to inform you of the rest

**Comment by AdriCilie** [comment]
Thank you very much! 

I managed to separate all the walls of the labyrinth thanks to your explanations! 

I now have another problem, it is that when I want to put a material on the walls of the maze, the textures do not appear..? I tried on other 3d software and I only have the color that is displayed, but not the texture of the hardware. Do you know where the problem comes from?

**Comment by Gorgious56** [comment]
I think the walls are not UV unwrapped, you'd have to do that manually. Thankfully they're just elongated cubes so a simple smart unwrap should do it ?

**Comment by AdriCilie** [comment]
That's right there is no uv map. 

Do you know how to apply UV to the mesh of each 3D object? 
I don't know "Blender" very well but I'll see if I find, and I'll get back to you. 

Thanks again!

**Comment by AdriCilie** [comment]
I managed to find the solution for textures.
Thank you again for your help and your plug-in that you made for blender. It is a golden job, very useful and well done.
This will make my work for my project much easier. This gives me ideas and knowledge for the blender software that will be useful for the work I do!

I want to ask you for your name or nickname as well as your website if you have one? So that I could, the figure in my project in the thanks of help to the realization of the project.

I want to keep in touch with you, and follow up to contact you again

Best regards

**Comment by Gorgious56** [comment]
Hey, I'm so glad you managed to do what you wanted ! 

I don't have much time to work on this plugin anymore unfortunately, but I have planned to upgrade it to leverage the Geometry Nodes which are available in recent versions.

I don't have a website but if you want to thank this work you can directly link to this repository and use my handle, @Gorgious56 (Nathan Hild is my real name). I do have a [linkedin page](https://www.linkedin.com/in/nathan-hild/) if you want to connect there. 

I'd be happy to see your final product and how I contributed :)

Cheers !

**Comment by AdriCilie** [comment]
Perfect, thank you. I could read that the license is CC0, that's why, I would not fail to write your name on the help of the "MazeGenerator" and put a link to this repository under your ID. 
It's the least I can do to help him bring to the project! 

Thank you again Nathan, I will contact you when my project will be published.
See you again
