### ISSUE TITLE
Not showing Up

### ISSUE THREAD

**Issue by masterats** [Gorgious56/MazeGenerator#2]
Hi,
I've installed the addon, however it hasn't showed up on the rightside of the 3d Viewport.  Not sure what I'm doing wrong.  Any help would be appreciated :).

**Comment by Gorgious56** [comment]
Hello ! Thanks for the interset :)
So, in order to help, a few questions :
 What blender version are you using ?
 Did you download the latest release of the add-on (0.3.0) ? https://github.com/Gorgious56/MazeGenerator/releases/download/0.3.0/Blender-MazeGenerator-0.3.0.zip
How did you install it / How familiar are you with add-ons installation ?

**Comment by masterats** [comment]
Hi,
I'm using blender version 2.83.
I can confirm I do have the latest version of the add-on (0.30)
![Blender Add-ons](https://user-images.githubusercontent.com/66627529/84389186-985c3500-abed-11ea-9b57-bac15e0b2794.png)
I'm not 100% familiar with the add-on installation.  However, I did follow some online tutorials.

Any advice/help you can offer will be greatly appreciated.

**Comment by Gorgious56** [comment]
Is there some kind of error shown in the console window when you go to
Window > Toggle System Console ?
Also, Can you try disabling the add-on, removing it with the button,
quitting blender then trying to re-enabling it ?

To install the add-on, you are supposed to go to install > Then choose
directly the .zip file downloaded from here. But it seems you did that
alright.
Maybe you can try with an earlier version after removing this one if this
doesn't work ?

**Comment by aecii** [comment]
I had the same issue with the add-on not showing up in b 2.83.0 
Master wont install for me. Downloaded the one mentioned above by owner and that one installed fine: 
https://github.com/Gorgious56/MazeGenerator/releases/download/0.3.0/Blender-MazeGenerator-0.3.0.zip

**Comment by Gorgious56** [comment]
Yes I should definitely reorder things so that the master works out of the box, but most of the times there are some buggy features in there so you should get the "official" releases instead. :) Do you have any feedback you'd care to share ??

**Comment by mlo0352** [comment]
So I used the 0.3.0 install with the latest version of Blender. I don't see the addon in any menus. Where should it be located by default?

**Comment by Gorgious56** [comment]
It's located in the "N" panel on the right of the 3D view.

![image](https://user-images.githubusercontent.com/25156105/125907887-ae39e516-ca90-47a8-9056-9a280e93bef0.png)

If the panel is closed, you can open it with the shortcut "N" by default of clicking on this arrow :

![image](https://user-images.githubusercontent.com/25156105/125907969-1d151f0d-411d-48e8-b63e-470c1468e2d0.png)
