### ISSUE TITLE
installing of newest version fails...doesn't show up

### ISSUE THREAD

**Issue by luckychris** [Gorgious56/MazeGenerator#6]
It's a bit embarrassing to me and i hope i made something wrong but on my m1 mac i cannot install your latest version. It does not show up in the add-on list. However the 3.0 version does show up.

**Comment by Gorgious56** [comment]
Hello !

Could you elaborate on what you mean when yo usay the 3.0 version shows up ?

**Comment by luckychris** [comment]
I meant the 0.3.0 version of maze generator works. But the latest version, if I try to install, the name won’t appear in the list.

**Comment by Gorgious56** [comment]
Did you download [this version](https://github.com/Gorgious56/MazeGenerator/releases/download/0.4.0/Blender-MazeGenerator-0.4.0.zip) ? If you download the source code directly you won't be able to directly install it as a package since the addon code will be in a subfolder.

**Comment by luckychris** [comment]
Worked. Thank you!! Sorry for my dumb question....

**Comment by Gorgious56** [comment]
No problem, I'm planning on refactoring the folder structure to work out of the box in the next version. :) Cheers

**Comment by luckychris** [comment]
Great!
